version: '3'
services: 
  apache: 
    build: ./apache 
    ports: 
      - "80:80"
    network_mode: "host" 
    container_name: "apache"
  rmi: 
    build: ./rmi 
    ports: 
      - "1099:1099"
    network_mode: "host"
    environment:
      - SYSTEM_IP=159.65.23.223
    depends_on:
      - "apache"
    command: ["./wait-for-it.sh", "apache:80", "--", "java", "-cp", ":./junit.jar:./ct414.jar:./hamcrest.jar", "-Djava.rmi.server.codebase=159.65.23.223/ct414.jar", "-Djava.rmi.server.hostname=159.65.23.223", "-Djava.security.policy=./server.policy", "server.ExamEngine"]
    container_name: "rmi"