FROM ubuntu

RUN apt-get install -y
RUN apt-get update
RUN apt-get install -y openjdk-8-jdk
RUN apt-get install -y apache2
RUN apt-get install -y wget
EXPOSE 80
RUN apachectl -k start
COPY ./ /usr/src
WORKDIR /usr/src/
RUN wget https://search.maven.org/remotecontent?filepath=junit/junit/4.12/junit-4.12.jar -O junit.jar
RUN wget https://search.maven.org/remotecontent?filepath=org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar -O hamcrest.jar
WORKDIR /usr/src/src/
RUN javac common/*.java
RUN jar cvf ct414.jar common/*.class
WORKDIR /usr/src/src/ie/nuigalway/ct414/assignment1/neelydaly/
EXPOSE 1099
RUN rmiregistry &
RUN javac -cp ./usr/usr/src/*.jar:./usr/src/*.jar server/*.java
CMD ["java", "server/ExamEngine.java"]