version: '3'
services: 
  apache: 
    build: ./apache 
    ports: 
      - "80:80"
    network_mode: "host" 
    container_name: "apache"
  rmi: 
    build: ./rmi 
    ports: 
      - "1099:1099"
    network_mode: "host"
    environment:
      - SYSTEM_IP=159.65.23.223
    container_name: "rmi"